sudo: required
services:
    - docker

before_install:
    - docker build -t spud.aldridge/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true spud.aldridge/react npm test -- --coverage


after_success:
    - docker build -t spud.aldridge/multi-client ./client
    - docker build -t spud.aldridge/multi-nginx ./nginx
    - docker build -t spud.aldridge/multi-server ./server
    - docker build -t spud.aldridge/multi-worker ./worker
    # Login to the docker CLI
    # encrypted environment variables from travis ci
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    # push image to docker hub
    - docker push spud.aldridge/multi-client
    - docker push spud.aldridge/multi-nginx
    - docker push spud.aldridge/multi-server
    - docker push spud.aldridge/multi-worker
